### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by Riroaki** [CPF-NLPR/IncrementalED#1]
Thanks for your great work! However, I wonder whether you could give some explanations about the data format in your codes? To exemplify this, what does the `7` mean in the following sample?
`The same official said the IMF also insists that the good sections of the two banks be merged .	7	contact`

**Comment by CPF-NLPR** [comment]
> Thanks for your great work! However, I wonder whether you could give some explanations about the data format in your codes? To exemplify this, what does the `7` mean in the following sample?
> `The same official said the IMF also insists that the good sections of the two banks be merged . 7 contact`

Thanks for your interest in our work.  The data format is:
sentence (split by space), the position of trigger word in the sentence, the type of the trigger. They are splitted by the '\t'.

**Comment by Riroaki** [comment]
Thanks for your reply, and what if the trigger contains more than one word? The position here seems to indicate the starting point only.

**Comment by CPF-NLPR** [comment]
> Thanks for your reply, and what if the trigger contains more than one word? The position here seems to indicate the starting point only.

Since most of trigger is only one word, we use the first word as the trigger if the trigger contains more than one word.

**Comment by Riroaki** [comment]
Thanks again!
